### Importar bibliotecas

In [1]:
import pandas as pd
import numpy as np
from pycaret.classification import *
from pycaret.datasets import get_data

### Carregar Dados

In [2]:
df = get_data('juice')
print(df.shape)

,Id,Purchase,WeekofPurchase,StoreID,PriceCH,PriceMM,DiscCH,DiscMM,SpecialCH,SpecialMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,Store7,PctDiscMM,PctDiscCH,ListPriceDiff,STORE
0,1,CH,237,1,1.75,1.99,0.00,0.0,0,0,0.500000,1.99,1.75,0.24,No,0.000000,0.000000,0.24,1
1,2,CH,239,1,1.75,1.99,0.00,0.3,0,1,0.600000,1.69,1.75,-0.06,No,0.150754,0.000000,0.24,1
2,3,CH,245,1,1.86,2.09,0.17,0.0,0,0,0.680000,2.09,1.69,0.40,No,0.000000,0.091398,0.23,1
3,4,MM,227,1,1.69,1.69,0.00,0.0,0,0,0.400000,1.69,1.69,0.00,No,0.000000,0.000000,0.00,1
4,5,CH,228,7,1.69,1.69,0.00,0.0,0,0,0.956535,1.69,1.69,0.00,Yes,0.000000,0.000000,0.00,0

(1070, 19)

### Preparar o setup do Pycaret

In [3]:
setup1= setup(data = df,
              target = 'Purchase',
              normalize= True,
              normalize_method= 'minmax',
              silent= True

              )

In [4]:
get_config(variable= "X_train")

,WeekofPurchase,PriceCH,PriceMM,DiscCH,DiscMM,LoyalCH,SalePriceMM,SalePriceCH,PriceDiff,ListPriceDiff,StoreID_1,StoreID_2,StoreID_3,SpecialCH_0,SpecialMM_0,STORE_4
788,0.921568,0.425,0.733334,0.94,0.675,0.500018,0.363636,0.000000,0.664122,0.613636,0.0,0.0,0.0,0.0,1.0,0.0
513,0.823529,0.750,0.666667,0.20,0.000,0.967066,0.818182,0.714286,0.664122,0.227273,0.0,0.0,1.0,1.0,1.0,0.0
529,0.176470,0.150,0.500000,0.00,0.500,0.600025,0.363636,0.514286,0.389313,0.545455,0.0,0.0,0.0,1.0,1.0,0.0
978,0.980392,0.750,0.733334,0.48,0.000,0.103195,0.854546,0.514286,0.801527,0.318182,1.0,0.0,0.0,1.0,1.0,0.0
384,0.000000,0.000,0.000000,0.00,0.000,0.258396,0.454545,0.428572,0.511450,0.000000,0.0,1.0,0.0,1.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
217,0.784314,0.425,0.733334,0.00,0.000,0.984008,0.854546,0.671429,0.717557,0.613636,0.0,0.0,0.0,0.0,1.0,0.0
652,0.647059,0.425,0.816667,0.00,0.875,0.944709,0.263636,0.671429,0.221374,0.727273,0.0,1.0,0.0,1.0,1.0,0.0
576,0.058824,0.000,0.500000,0.00,0.000,0.600025,0.727273,0.428572,0.740458,0.681818,0.0,0.0,0.0,1.0,0.0,0.0
492,0.352941,0.750,0.900000,0.00,0.000,0.916161,0.945455,0.857143,0.694656,0.545455,0.0,0.0,1.0,1.0,1.0,0.0
805,0.627451,0.425,0.816667,0.00,0.000,0.680031,0.900000,0.671429,0.755725,0.727273,0.0,0.0,0.0,1.0,1.0,0.0

### Treinar diferentes modelos

In [6]:
compare_models( sort= 'AUC')

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=1000,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=4340, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [7]:
model = create_model('lr')

In [8]:
tuned_model= tune_model(model, n_iter = 100, choose_better= True)

In [9]:
evaluate_model(model)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'param…

### Salvar o modelo para o deploy

In [ ]:
finalize_model(tuned_model)
save_model(tuned_model,'final_model')